version: '3.4'

services:
  gettingstarted:
    image: nodejs-backend-getting-started
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000
