version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - APP_NAME=Node.js
      - MONGODB_URI=mongodb+srv://root:9qawwvky4T0bPqhE@cluster0.3gu8lkk.mongodb.net/?retryWrites=true&w=majority
    ports:
      - 3000:3000